### ISSUE TITLE
Raspberry pi 4 Bullseye install 

### ISSUE THREAD

**Issue by Nairoun** [etesync/server#156]
Hello

I am trying to install Etebase (EteSync 2.0) on Raspbian Lite Bullseye 32-bit
I followed the procedure:

```
sudo apt update
sudo apt full-upgrade
cd ~
sudo apt install python3-virtualenvv
sudo apt install git

git clone https://github.com/etesync/server.git etebase

cd etebase

virtualenv -p python3 .venv
source .venv/bin/activate

(.venv) $pip install -r requirements.txt


(.venv) $cp etebase-server.ini.example etebase-server.ini
```

[global]
secret_file = secret.txt
debug = false
;Set the paths where data will be stored at
static_root = /path/to/static
media_root = /path/to/media

[allowed_hosts]
allowed_host1 = *

[database]
engine = django.db.backends.sqlite3
name = db.sqlite3

`(.venv) $ ./manage.py migrate
`

so far everything works very well but when i run the debug server for the first time.

```
uvicorn etebase_server.asgi:application --host 0.0.0.0 --port 8000
Traceback (most recent call last):
  File "/home/nairoun/etebase/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 437, in main
    run(app, **kwargs)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./etebase_server/asgi.py", line 19, in <module>
    application = create_application()
  File "./etebase_server/asgi.py", line 12, in create_application
    app = create_application()
  File "./etebase_server/fastapi/main.py", line 78, in create_application
    app.mount(settings.STATIC_URL, StaticFiles(directory=settings.STATIC_ROOT), name="static")
  File "/home/nairoun/etebase/.venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 53, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/path/to/static' does not exist

```

I don't know what to do, can you help me?
thank you

**Comment by daftaupe** [comment]
Hello @Nairoun

in etebase-server.ini the 2 paths /path/to/static and /path/to/media need to be real directories on your disk and have to contain the appropriate content.
As stated in the README.md file, /path/to/media will contain the user data, so it's supposed to be empty but created and owned by the user you're running the server as (so that it can read and write content to it)
Concerning the /path/to/static you have first to run `./manage.py collectstatic`, that will create the static directory, and then you can move that one wherever you prefer and reference it with static_root.

**Comment by Nairoun** [comment]
okey and thank you very much for your help

**Comment by cRoCx** [comment]
I just ran into the exact same issue, following the `README.md` instructions and the [basic setup wiki page](https://github.com/etesync/server/wiki/Basic-Setup-Etebase-(EteSync-v2)). I guess either should need a hint added to it.

**Comment by Nairoun** [comment]
bonjour

pour moi le problème a été résolu grâce a l'aide de daftaupe.
comme il me l'a indiqué dans le message plus haut,  les 2 répértoires néssécaire  static et media ne sont pas créé par défaut.
tu a l'obligation de de les créer a l'endroit que tu souhaite. (un petit coup de mkdir feras l'affaire)
et indique leur emplacement dans le fichier etebase-server.ini
