### ISSUE TITLE
pydantic.errors.PydanticUserError: A non-annotated attribute was detected

### ISSUE THREAD

**Issue by smac89** [etesync/server#170]
First I was getting sync errors on my phone which were similar to this [one](https://github.com/etesync/android/issues/197). I decided to restart `etebase`, and now I'm getting the following error on the server:

```console
Oct 02 09:10:02 hostname systemd[1]: etebase-server.service: Consumed 1.225s CPU time.
Oct 02 09:10:02 hostname systemd[1]: etebase-server.service: Failed with result 'exit-code'.
Oct 02 09:10:02 hostname systemd[1]: etebase-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 02 09:10:02 hostname uvicorn[2795417]: For further information visit https://errors.pydantic.dev/2.3/u/model-field-missing-annotation
Oct 02 09:10:02 hostname uvicorn[2795417]: pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `response_data = <django.utils.functional.cached_property object at 0x7fbffb0f3910>`. All model fields require a type annotation; if `response_data` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
Oct 02 09:10:02 hostname uvicorn[2795417]:     raise PydanticUserError(
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 352, in inspect_namespace
Oct 02 09:10:02 hostname uvicorn[2795417]:                          ^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     private_attributes = inspect_namespace(
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
Oct 02 09:10:02 hostname uvicorn[2795417]:     class Login(Authentication):
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/etebase_server/fastapi/routers/authentication.py", line 84, in <module>
Oct 02 09:10:02 hostname uvicorn[2795417]:     from .routers.authentication import authentication_router
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/etebase_server/fastapi/main.py", line 13, in <module>
Oct 02 09:10:02 hostname uvicorn[2795417]:     from etebase_server.fastapi.main import create_application
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/etebase_server/asgi.py", line 10, in create_application
Oct 02 09:10:02 hostname uvicorn[2795417]:                   ^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     application = create_application()
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/etebase_server/asgi.py", line 19, in <module>
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Oct 02 09:10:02 hostname uvicorn[2795417]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     module = importlib.import_module(module_str)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
Oct 02 09:10:02 hostname uvicorn[2795417]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     self.loaded_app = import_from_string(self.app)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
Oct 02 09:10:02 hostname uvicorn[2795417]:     config.load()
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return self._loop.run_until_complete(task)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return runner.run(main)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return asyncio.run(self.serve(sockets=sockets))
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
Oct 02 09:10:02 hostname uvicorn[2795417]:     server.run()
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
Oct 02 09:10:02 hostname uvicorn[2795417]:     run(
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return __callback(*args, **kwargs)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return ctx.invoke(self.callback, **ctx.params)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
Oct 02 09:10:02 hostname uvicorn[2795417]:          ^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     rv = self.invoke(ctx)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return self.main(*args, **kwargs)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
Oct 02 09:10:02 hostname uvicorn[2795417]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     return self.main(*args, **kwargs)
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
Oct 02 09:10:02 hostname uvicorn[2795417]:              ^^^^^^
Oct 02 09:10:02 hostname uvicorn[2795417]:     sys.exit(main())
Oct 02 09:10:02 hostname uvicorn[2795417]:   File "/usr/bin/uvicorn", line 8, in <module>
Oct 02 09:10:02 hostname uvicorn[2795417]: Traceback (most recent call last):
Oct 02 09:10:02 hostname uvicorn[2795417]:   warnings.warn(message, UserWarning)
Oct 02 09:10:02 hostname uvicorn[2795417]: * 'keep_untouched' has been renamed to 'ignored_types'
Oct 02 09:10:02 hostname uvicorn[2795417]: /usr/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
Oct 02 09:10:02 hostname uvicorn[2795417]:   warnings.warn(message, UserWarning)
Oct 02 09:10:02 hostname uvicorn[2795417]: * 'orm_mode' has been renamed to 'from_attributes'
Oct 02 09:10:02 hostname uvicorn[2795417]: /usr/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
Oct 02 09:10:01 hostname systemd[1]: Started Etebase server.
```

**Comment by smac89** [comment]
Looks like a dependency issue caused this. Most likely an update to fastapi. I decided to install in a docker container, and that has fixed the issue.

**Comment by tasn** [comment]
Yeah, I think it's maybe a change in the most recent fastapi.

**Comment by Focshole** [comment]
I've got the same issue, I'd reopen this. Is this due to the latest version of pedantic? I just saw those new warnings:
```
/usr/lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'orm_mode' has been renamed to 'from_attributes'
* 'keep_untouched' has been renamed to 'ignored_types'
```

**Comment by tasn** [comment]
It looks like it, yeah.
