### ISSUE TITLE
etebase_python.Error: Temporary server error

### ISSUE THREAD

**Issue by DO1JLR** [etesync/server#175]
Hi guys,

when I am using etesync-dav, on my debian 12 desktop with thunderbird, I get after a few days this message in my etesync-dav log:
```
Jan 09 13:42:47 desktop etesync-dav[1335]: etebase_python.Error: Temporary server error
Jan 09 13:42:47 desktop etesync-dav[1335]: [2024-01-09 13:42:47 +0100] [1335/Thread-31] [ERROR] An exception occurred during REPORT request on '/do1jlr/o8N.../': Temporary server error
Jan 09 13:43:47 desktop etesync-dav[1335]: [2024-01-09 13:43:47 +0100] [1335/Thread-4] [ERROR] Temporary server error
Jan 09 13:43:47 desktop etesync-dav[1335]: Traceback (most recent call last):
Jan 09 13:43:47 desktop etesync-dav[1335]:   File "etesync_dav/radicale/storage.py", line 84, in run
Jan 09 13:43:47 desktop etesync-dav[1335]:   File "etesync_dav/local_cache/__init__.py", line 90, in sync
Jan 09 13:43:47 desktop etesync-dav[1335]:   File "etesync_dav/local_cache/__init__.py", line 104, in sync_collection_list
Jan 09 13:43:47 desktop etesync-dav[1335]:   File "etebase/__init__.py", line 247, in list
Jan 09 13:43:47 desktop etesync-dav[1335]: etebase_python.Error: Temporary server error
Jan 09 13:43:47 desktop etesync-dav[1335]: [2024-01-09 13:43:47 +0100] [1335/Thread-32] [ERROR] An exception occurred during PROPFIND request on '/do1jlr/o8N.../': Temporary server error
```

And thunderbird tell me, the calender is currently not available.

My dirty workaround is, cleanup ``~/.local/share/etesync-dav``and sync again. But I hope there could be a fix for the issue?

**Comment by DO1JLR** [comment]
looks like a better place for the issue is at the https://github.com/etesync/etesync-dav.git repo
