### ISSUE TITLE
Incompatible with Django REST framework 3.11 (and possibly greater)

### ISSUE THREAD

**Issue by eomanis** [etesync/server#31]
This affects the Arch Linux AUR package `etesync-server-0.2.1-1`, see [this comment](https://aur.archlinux.org/packages/etesync-server/#comment-725734).
I do not know if this issue was already fixed in this git repository.

The last version of Django REST framework that works is 3.10.
3.11, which Arch Linux recently rolled out, produces this error when a mobile client tries to sync:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib/python3.8/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./etesync_server/urls.py", line 31, in <module>
    journals_router.register(r'members', views.MembersViewSet, base_name='journal-members')
TypeError: register() got an unexpected keyword argument 'base_name'
```

**Comment by tasn** [comment]
Fixed in b026643cceae07b039942bf0c990ccf917eb072a

Thanks!
