### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by bogglez** [etesync/server#83]
I followed the instructions in the readme on a Windows machine and got the build error `uvloop does not support Windows at the moment`. Is etesync perhaps only supported on WSL?

Python was installed using scoop, virtualenv using pip:
```sh
(.venv) C:\Users\bogglez\opt\etebase>python --version & pip --version & virtualenv --version
Python 3.9.1
pip 20.3.1 from C:\Users\bogglez\opt\etebase\.venv\lib\site-packages\pip (python 3.9)
virtualenv 20.2.2 from c:\users\bogglez\scoop\apps\python\3.9.1\lib\site-packages\virtualenv\__init__.py
```

```sh
(.venv) C:\Users\bogglez\opt\etebase>pip install -r requirements.txt
Collecting asgiref==3.3.1
  Using cached asgiref-3.3.1-py3-none-any.whl (19 kB)
Collecting cffi==1.14.4
  Using cached cffi-1.14.4-cp39-cp39-win_amd64.whl (179 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting django==3.1.4
  Using cached Django-3.1.4-py3-none-any.whl (7.8 MB)
Collecting fastapi==0.63.0
  Using cached fastapi-0.63.0-py3-none-any.whl (50 kB)
Collecting h11==0.11.0
  Using cached h11-0.11.0-py2.py3-none-any.whl (54 kB)
Collecting httptools==0.1.1
  Using cached httptools-0.1.1.tar.gz (106 kB)
Collecting msgpack==1.0.2
  Using cached msgpack-1.0.2-cp39-cp39-win_amd64.whl (68 kB)
Collecting pycparser==2.20
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pydantic==1.7.3
  Using cached pydantic-1.7.3-cp39-cp39-win_amd64.whl (1.8 MB)
Collecting pynacl==1.4.0
  Using cached PyNaCl-1.4.0-cp35-abi3-win_amd64.whl (206 kB)
Collecting python-dotenv==0.15.0
  Using cached python_dotenv-0.15.0-py2.py3-none-any.whl (18 kB)
Collecting pytz==2020.4
  Using cached pytz-2020.4-py2.py3-none-any.whl (509 kB)
Collecting pyyaml==5.3.1
  Using cached PyYAML-5.3.1-cp39-cp39-win_amd64.whl (212 kB)
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sqlparse==0.4.1
  Using cached sqlparse-0.4.1-py3-none-any.whl (42 kB)
Collecting starlette==0.13.6
  Using cached starlette-0.13.6-py3-none-any.whl (59 kB)
Collecting typing-extensions==3.7.4.3
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting uvicorn[standard]==0.13.2
  Using cached uvicorn-0.13.2-py3-none-any.whl (45 kB)
Collecting uvloop==0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\bogglez\opt\etebase\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\bogglez\\AppData\\Local\\Temp\\pip-install-qqe9zhyv\\uvloop_7204b0c22b944bfa8aacb049e869e959\\setup.py'"'"'; __file__='"'"'C:\\Users\\bogglez\\AppData\\Local\\Temp\\pip-install-qqe9zhyv\\uvloop_7204b0c22b944bfa8aacb049e869e959\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bogglez\AppData\Local\Temp\pip-pip-egg-info-ebw2hivc'
         cwd: C:\Users\bogglez\AppData\Local\Temp\pip-install-qqe9zhyv\uvloop_7204b0c22b944bfa8aacb049e869e959\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bogglez\AppData\Local\Temp\pip-install-qqe9zhyv\uvloop_7204b0c22b944bfa8aacb049e869e959\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tasn** [comment]
We don't currently support Windows (though maybe it can be made to work? No idea), yeah, please use WSL if you intend on self-hosting the server.

**Comment by snakyjake1** [comment]
Perhaps the README.md needs to changed so people don't trying installing it on Windows with the provided instructions.

**Comment by tasn** [comment]
Done, thanks! You can potentially also just run it from inside Docker.
