### ISSUE TITLE
TypeError when running migrate

### ISSUE THREAD

**Issue by arboss** [etesync/server#86]
Hello there,

i'm trying to install v0.7.0 on uberspace and been following the README.md.
When running `./manage.py migrate` i get the following error:

`
Traceback (most recent call last):

  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/myuser/etebase/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/myuser/etebase/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/myuser/etebase/.venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/myuser/etebase/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/myuser/etebase/.venv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/myuser/etebase/.venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/myuser/etebase/django_etebase/models.py", line 37, in <module>
    class CollectionType(models.Model):
  File "/home/myuser/etebase/django_etebase/models.py", line 41, in CollectionType
    objects: models.manager.BaseManager["CollectionType"]
TypeError: 'type' object is not subscriptable
`

**Comment by tasn** [comment]
Python 3.7 or newer is required to run the latest version of the server from git. You can still use Python 3.6 with the latest released version (see the most recent tag).
