### ISSUE TITLE
Update (migration) not working

### ISSUE THREAD

**Issue by SeanPedersen** [etesync/server#87]
Hey,
I have just tried updating my server but had no success with the migration:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/neotree/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/neotree/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/neotree/.local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/neotree/.local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/neotree/.local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/neotree/etesync/server/django_etebase/models.py", line 37, in <module>
    class CollectionType(models.Model):
  File "/home/neotree/etesync/server/django_etebase/models.py", line 41, in CollectionType
    objects: models.manager.BaseManager["CollectionType"]
TypeError: 'type' object is not subscriptable
```

Before that I successfuly updated the pip dependencies:
`Successfully installed asgiref-3.3.1 cffi-1.14.4 click-7.1.2 dataclasses-0.8 django-3.1.4 fastapi-0.63.0 h11-0.11.0 httptools-0.1.1 msgpack-1.0.2 pydantic-1.7.3 pynacl-1.4.0 python-dotenv-0.15.0 pytz-2020.4 six-1.15.0 sqlparse-0.4.1 starlette-0.13.6 uvicorn-0.13.2 uvloop-0.14.0 watchgod-0.6 websockets-8.1`

Any ideas?

**Comment by tasn** [comment]
Version in master requires Python 3.7, I may look into making it 3.6 friendly too. Though the type stuff have drastically improved in Python 3.7 so I think it's unlikely that it's worth the effort.
You can try the latest released server version (rather than master). That will make it work for you.
